// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/ai_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_ProcessFrame_FullMethodName       = "/ai_service.AIService/ProcessFrame"
	AIService_ProcessBatchFrames_FullMethodName = "/ai_service.AIService/ProcessBatchFrames"
	AIService_GetModelInfo_FullMethodName       = "/ai_service.AIService/GetModelInfo"
	AIService_GetServerStats_FullMethodName     = "/ai_service.AIService/GetServerStats"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	ProcessFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameResponse, error)
	ProcessBatchFrames(ctx context.Context, in *BatchFrameRequest, opts ...grpc.CallOption) (*BatchFrameResponse, error)
	GetModelInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelInfoResponse, error)
	GetServerStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerStatsResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) ProcessFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrameResponse)
	err := c.cc.Invoke(ctx, AIService_ProcessFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ProcessBatchFrames(ctx context.Context, in *BatchFrameRequest, opts ...grpc.CallOption) (*BatchFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchFrameResponse)
	err := c.cc.Invoke(ctx, AIService_ProcessBatchFrames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetModelInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfoResponse)
	err := c.cc.Invoke(ctx, AIService_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetServerStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatsResponse)
	err := c.cc.Invoke(ctx, AIService_GetServerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	ProcessFrame(context.Context, *FrameRequest) (*FrameResponse, error)
	ProcessBatchFrames(context.Context, *BatchFrameRequest) (*BatchFrameResponse, error)
	GetModelInfo(context.Context, *Empty) (*ModelInfoResponse, error)
	GetServerStats(context.Context, *Empty) (*ServerStatsResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) ProcessFrame(context.Context, *FrameRequest) (*FrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessFrame not implemented")
}
func (UnimplementedAIServiceServer) ProcessBatchFrames(context.Context, *BatchFrameRequest) (*BatchFrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessBatchFrames not implemented")
}
func (UnimplementedAIServiceServer) GetModelInfo(context.Context, *Empty) (*ModelInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedAIServiceServer) GetServerStats(context.Context, *Empty) (*ServerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStats not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_ProcessFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ProcessFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ProcessFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ProcessFrame(ctx, req.(*FrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ProcessBatchFrames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ProcessBatchFrames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ProcessBatchFrames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ProcessBatchFrames(ctx, req.(*BatchFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetModelInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetServerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetServerStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_service.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFrame",
			Handler:    _AIService_ProcessFrame_Handler,
		},
		{
			MethodName: "ProcessBatchFrames",
			Handler:    _AIService_ProcessBatchFrames_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _AIService_GetModelInfo_Handler,
		},
		{
			MethodName: "GetServerStats",
			Handler:    _AIService_GetServerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai_service.proto",
}
