// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ai_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameData     []byte                 `protobuf:"bytes,1,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"` // 'rgb', 'jpeg', 'yuv420'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *FrameRequest) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *FrameRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameRequest) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *FrameRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type BBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XMin          float32                `protobuf:"fixed32,1,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"`
	YMin          float32                `protobuf:"fixed32,2,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"`
	XMax          float32                `protobuf:"fixed32,3,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"`
	YMax          float32                `protobuf:"fixed32,4,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBox) Reset() {
	*x = BBox{}
	mi := &file_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *BBox) GetXMin() float32 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *BBox) GetYMin() float32 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *BBox) GetXMax() float32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *BBox) GetYMax() float32 {
	if x != nil {
		return x.YMax
	}
	return 0
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Bbox          *BBox                  `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *Detection) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

type AIResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detections    []*Detection           `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIResults) Reset() {
	*x = AIResults{}
	mi := &file_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIResults) ProtoMessage() {}

func (x *AIResults) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIResults.ProtoReflect.Descriptor instead.
func (*AIResults) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *AIResults) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

type FrameResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FrameId          string                 `protobuf:"bytes,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Timestamp        string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessingTimeMs float32                `protobuf:"fixed32,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	AiResults        *AIResults             `protobuf:"bytes,6,opt,name=ai_results,json=aiResults,proto3" json:"ai_results,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *FrameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FrameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FrameResponse) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *FrameResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FrameResponse) GetProcessingTimeMs() float32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *FrameResponse) GetAiResults() *AIResults {
	if x != nil {
		return x.AiResults
	}
	return nil
}

type BatchFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*FrameRequest        `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchFrameRequest) Reset() {
	*x = BatchFrameRequest{}
	mi := &file_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFrameRequest) ProtoMessage() {}

func (x *BatchFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFrameRequest.ProtoReflect.Descriptor instead.
func (*BatchFrameRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *BatchFrameRequest) GetFrames() []*FrameRequest {
	if x != nil {
		return x.Frames
	}
	return nil
}

type BatchFrameResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Responses           []*FrameResponse       `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	TotalProcessingTime float32                `protobuf:"fixed32,4,opt,name=total_processing_time,json=totalProcessingTime,proto3" json:"total_processing_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchFrameResponse) Reset() {
	*x = BatchFrameResponse{}
	mi := &file_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFrameResponse) ProtoMessage() {}

func (x *BatchFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFrameResponse.ProtoReflect.Descriptor instead.
func (*BatchFrameResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *BatchFrameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchFrameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchFrameResponse) GetResponses() []*FrameResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchFrameResponse) GetTotalProcessingTime() float32 {
	if x != nil {
		return x.TotalProcessingTime
	}
	return 0
}

type ModelInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ModelPath     string                 `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	InputInfo     map[string]string      `protobuf:"bytes,3,rep,name=input_info,json=inputInfo,proto3" json:"input_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OutputInfo    map[string]string      `protobuf:"bytes,4,rep,name=output_info,json=outputInfo,proto3" json:"output_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoResponse) Reset() {
	*x = ModelInfoResponse{}
	mi := &file_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoResponse) ProtoMessage() {}

func (x *ModelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoResponse.ProtoReflect.Descriptor instead.
func (*ModelInfoResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *ModelInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ModelInfoResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *ModelInfoResponse) GetInputInfo() map[string]string {
	if x != nil {
		return x.InputInfo
	}
	return nil
}

func (x *ModelInfoResponse) GetOutputInfo() map[string]string {
	if x != nil {
		return x.OutputInfo
	}
	return nil
}

type ServerStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PoolSize      int32                  `protobuf:"varint,2,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	InUse         int32                  `protobuf:"varint,3,opt,name=in_use,json=inUse,proto3" json:"in_use,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatsResponse) Reset() {
	*x = ServerStatsResponse{}
	mi := &file_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatsResponse) ProtoMessage() {}

func (x *ServerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatsResponse.ProtoReflect.Descriptor instead.
func (*ServerStatsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *ServerStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerStatsResponse) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *ServerStatsResponse) GetInUse() int32 {
	if x != nil {
		return x.InUse
	}
	return 0
}

func (x *ServerStatsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x10ai_service.proto\x12\n" +
	"ai_service\"\a\n" +
	"\x05Empty\"\x8f\x01\n" +
	"\fFrameRequest\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x01 \x01(\fR\tframeData\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"^\n" +
	"\x04BBox\x12\x13\n" +
	"\x05x_min\x18\x01 \x01(\x02R\x04xMin\x12\x13\n" +
	"\x05y_min\x18\x02 \x01(\x02R\x04yMin\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\"p\n" +
	"\tDetection\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12$\n" +
	"\x04bbox\x18\x03 \x01(\v2\x10.ai_service.BBoxR\x04bbox\"B\n" +
	"\tAIResults\x125\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2\x15.ai_service.DetectionR\n" +
	"detections\"\xe0\x01\n" +
	"\rFrameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bframe_id\x18\x03 \x01(\tR\aframeId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x02R\x10processingTimeMs\x124\n" +
	"\n" +
	"ai_results\x18\x06 \x01(\v2\x15.ai_service.AIResultsR\taiResults\"E\n" +
	"\x11BatchFrameRequest\x120\n" +
	"\x06frames\x18\x01 \x03(\v2\x18.ai_service.FrameRequestR\x06frames\"\xb5\x01\n" +
	"\x12BatchFrameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\tresponses\x18\x03 \x03(\v2\x19.ai_service.FrameResponseR\tresponses\x122\n" +
	"\x15total_processing_time\x18\x04 \x01(\x02R\x13totalProcessingTime\"\xe6\x02\n" +
	"\x11ModelInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tR\tmodelPath\x12K\n" +
	"\n" +
	"input_info\x18\x03 \x03(\v2,.ai_service.ModelInfoResponse.InputInfoEntryR\tinputInfo\x12N\n" +
	"\voutput_info\x18\x04 \x03(\v2-.ai_service.ModelInfoResponse.OutputInfoEntryR\n" +
	"outputInfo\x1a<\n" +
	"\x0eInputInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fOutputInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x13ServerStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tpool_size\x18\x02 \x01(\x05R\bpoolSize\x12\x15\n" +
	"\x06in_use\x18\x03 \x01(\x05R\x05inUse\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xad\x02\n" +
	"\tAIService\x12C\n" +
	"\fProcessFrame\x12\x18.ai_service.FrameRequest\x1a\x19.ai_service.FrameResponse\x12S\n" +
	"\x12ProcessBatchFrames\x12\x1d.ai_service.BatchFrameRequest\x1a\x1e.ai_service.BatchFrameResponse\x12@\n" +
	"\fGetModelInfo\x12\x11.ai_service.Empty\x1a\x1d.ai_service.ModelInfoResponse\x12D\n" +
	"\x0eGetServerStats\x12\x11.ai_service.Empty\x1a\x1f.ai_service.ServerStatsResponseB\x11Z\x0fgo_server/protob\x06proto3"

var (
	file_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_proto_rawDescData []byte
)

func file_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)))
	})
	return file_ai_service_proto_rawDescData
}

var file_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ai_service_proto_goTypes = []any{
	(*Empty)(nil),               // 0: ai_service.Empty
	(*FrameRequest)(nil),        // 1: ai_service.FrameRequest
	(*BBox)(nil),                // 2: ai_service.BBox
	(*Detection)(nil),           // 3: ai_service.Detection
	(*AIResults)(nil),           // 4: ai_service.AIResults
	(*FrameResponse)(nil),       // 5: ai_service.FrameResponse
	(*BatchFrameRequest)(nil),   // 6: ai_service.BatchFrameRequest
	(*BatchFrameResponse)(nil),  // 7: ai_service.BatchFrameResponse
	(*ModelInfoResponse)(nil),   // 8: ai_service.ModelInfoResponse
	(*ServerStatsResponse)(nil), // 9: ai_service.ServerStatsResponse
	nil,                         // 10: ai_service.ModelInfoResponse.InputInfoEntry
	nil,                         // 11: ai_service.ModelInfoResponse.OutputInfoEntry
}
var file_ai_service_proto_depIdxs = []int32{
	2,  // 0: ai_service.Detection.bbox:type_name -> ai_service.BBox
	3,  // 1: ai_service.AIResults.detections:type_name -> ai_service.Detection
	4,  // 2: ai_service.FrameResponse.ai_results:type_name -> ai_service.AIResults
	1,  // 3: ai_service.BatchFrameRequest.frames:type_name -> ai_service.FrameRequest
	5,  // 4: ai_service.BatchFrameResponse.responses:type_name -> ai_service.FrameResponse
	10, // 5: ai_service.ModelInfoResponse.input_info:type_name -> ai_service.ModelInfoResponse.InputInfoEntry
	11, // 6: ai_service.ModelInfoResponse.output_info:type_name -> ai_service.ModelInfoResponse.OutputInfoEntry
	1,  // 7: ai_service.AIService.ProcessFrame:input_type -> ai_service.FrameRequest
	6,  // 8: ai_service.AIService.ProcessBatchFrames:input_type -> ai_service.BatchFrameRequest
	0,  // 9: ai_service.AIService.GetModelInfo:input_type -> ai_service.Empty
	0,  // 10: ai_service.AIService.GetServerStats:input_type -> ai_service.Empty
	5,  // 11: ai_service.AIService.ProcessFrame:output_type -> ai_service.FrameResponse
	7,  // 12: ai_service.AIService.ProcessBatchFrames:output_type -> ai_service.BatchFrameResponse
	8,  // 13: ai_service.AIService.GetModelInfo:output_type -> ai_service.ModelInfoResponse
	9,  // 14: ai_service.AIService.GetServerStats:output_type -> ai_service.ServerStatsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ai_service_proto_init() }
func file_ai_service_proto_init() {
	if File_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_depIdxs,
		MessageInfos:      file_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_proto = out.File
	file_ai_service_proto_goTypes = nil
	file_ai_service_proto_depIdxs = nil
}
